### ISSUE TITLE
About highlighting and annotation icon configuration

### ISSUE THREAD

**Issue by qlibp** [zaeph/.emacs.d#3]
Dear zaeph,

After watching your youtube video, demonstrating the orb package, I'm interested in 2 features in your emacs configurations.

1. When you jump between different notes, your line highlight seems pretty neat, how could I achieve this?
2. In your video, the annotation icon shown in document buffer, looks like "->" this, while mine is just a just grey rectangle.

I'm using doom emacs.

Thx in advance.

**Comment by zaeph** [comment]
Hi there,

> When you jump between different notes, your line highlight seems pretty neat, how could I achieve this?

cf. https://github.com/Malabarba/beacon

> In your video, the annotation icon shown in document buffer, looks like "->" this, while mine is just a just grey rectangle.

It could be a missing dependency.  I think it uses `imagemagick`'s `display` to show the image at the right location and without a border, but I can't tell you exactly what's going on on your end.  Try to figure out which lib `pdf-tools` is using to generate those pictures, and you should be able to find a solution.
